In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame as df
import datetime as dt
from datetime import timedelta
import json
import os
import csv
import matplotlib.pyplot as plt

In [2]:
localdir=os.getcwd()
# localdir

In [3]:
folder=[folder for folder in os.listdir(localdir) if 'experiments data' in folder][0]
print(folder, os.listdir(folder), len(os.listdir(folder)))

experiments data ['A1_barterGame.json', 'A1_ChatIncludeWhisper.log', 'A2_barterGame.json', 'A2_ChatIncludeWhisper.log', 'A3_barterGame.json', 'A3_ChatIncludeWhisper.log', 'A4_barterGame.json', 'A4_ChatIncludeWhisper.log', 'A5_barterGame.json', 'A5_ChatIncludeWhisper.log', 'A6_barterGame.json', 'A6_ChatIncludeWhisper.log', 'A7_barterGame.txt', 'A7_ChatIncludeWhisper.log', 'B1_barterGame.json', 'B1_ChatIncludeWhisper.log', 'B2_barterGame.json', 'B2_ChatIncludeWhisper.log', 'B3_barterGame.json', 'B3_ChatIncludeWhisper.log', 'B4_barterGame.json', 'B4_ChatIncludeWhisper.log', 'B5_barterGame.json', 'B5_ChatIncludeWhisper.log', 'B6_barterGame.json', 'B6_ChatIncludeWhisper.log', 'C1_barterGame.json', 'C1_ChatIncludeWhisper.log', 'C2_barterGame.json', 'C2_ChatIncludeWhisper.log', 'C3_barterGame.json', 'C3_ChatIncludeWhisper.log', 'C4_barterGame.json', 'C4_ChatIncludeWhisper.log', 'C5_barterGame.json', 'C5_ChatIncludeWhisper.log', 'C6_barterGame.json', 'C6_ChatIncludeWhisper.log', 'C7_barterGame.txt', 'C7_ChatIncludeWhisper.log', 'updated a1 a3 a4 c4 c5'] 41

In [4]:
json_files = [filename for filename in os.listdir(folder) if '.json' in filename or '.txt' in filename]
json_files, len(json_files)

(['A1_barterGame.json',
  'A2_barterGame.json',
  'A3_barterGame.json',
  'A4_barterGame.json',
  'A5_barterGame.json',
  'A6_barterGame.json',
  'A7_barterGame.txt',
  'B1_barterGame.json',
  'B2_barterGame.json',
  'B3_barterGame.json',
  'B4_barterGame.json',
  'B5_barterGame.json',
  'B6_barterGame.json',
  'C1_barterGame.json',
  'C2_barterGame.json',
  'C3_barterGame.json',
  'C4_barterGame.json',
  'C5_barterGame.json',
  'C6_barterGame.json',
  'C7_barterGame.txt'],
 20)

In [5]:
ACCEPTED = 'ACCEPTED'
DECLINED = 'DECLINED'
CANCELLED = 'CANCELLED'

game_trades_df_dict = {}
game_final_df_dict = {}
game_list = []
gametype_list = []
winner_list = []
score_list = []

player_profession_dict = {}
player_endscores_dict = {}

for filename in json_files:
    print(filename)
    gamename = filename.split('_barterGame')[0]
    data=open(os.path.join(localdir,folder,filename), encoding='utf8')
    data_load=json.load(data)
    data_load=data_load['barterGames'][0]

    player_profession_dict[filename] = {}
    player_endscores_dict[filename] = {}
    for ent in data_load['participants']:
        player_profession_dict[filename][ent['name']] = ent['profession'] 
#         if 'score' in ent:
        player_endscores_dict[filename][ent['name']] = ent['score']

    trades_df=df.from_records(data_load["trades"])
    for ind in trades_df.index:
        trades_df.loc[ind,"beginTimestamp"]=pd.Timestamp(trades_df.loc[ind,"beginTimestamp"])
        trades_df.loc[ind,"endTimestamp"]=pd.Timestamp(trades_df.loc[ind,"endTimestamp"])
    print(trades_df.shape, filename)
    # trades_df = trades_df[trades_df['status'].isin([ACCEPTED, CANCELLED, DECLINED])]
#     trades_df = trades_df[trades_df['status']==ACCEPTED]

    print(trades_df.shape, filename)
    game_trades_df_dict[filename] = trades_df
    # final_df=df.from_records(data_load['participants'])
    # game_final_df_dict[filename] = final_df
    # winner_list.append(data_load['winner'])
    # game_list.append(filename.split('_')[1])
    # if 'A' in filename.split('_')[1]:
    #     gametype_list.append('Competitive')
    # elif 'B' in filename.split('_')[1]:
    #     gametype_list.append('Baseline')
    # else:
    #     gametype_list.append('Cooperative')
    # score_list.append(data_load['score'])

# winner_df = df({'game':game_list, 'gametype':gametype_list, 'winner':winner_list,'score':score_list})
professions_set = set([player_profession_dict[folder][player] for folder in player_profession_dict for player in player_profession_dict[folder]])
# player_endscores_dict

A1_barterGame.json
(102, 9) A1_barterGame.json
(102, 9) A1_barterGame.json
A2_barterGame.json
(63, 11) A2_barterGame.json
(63, 11) A2_barterGame.json
A3_barterGame.json
(118, 11) A3_barterGame.json
(118, 11) A3_barterGame.json
A4_barterGame.json
(65, 11) A4_barterGame.json
(65, 11) A4_barterGame.json
A5_barterGame.json
(53, 13) A5_barterGame.json
(53, 13) A5_barterGame.json
A6_barterGame.json
(89, 13) A6_barterGame.json
(89, 13) A6_barterGame.json
A7_barterGame.txt
(54, 13) A7_barterGame.txt
(54, 13) A7_barterGame.txt
B1_barterGame.json
(66, 9) B1_barterGame.json
(66, 9) B1_barterGame.json
B2_barterGame.json
(88, 11) B2_barterGame.json
(88, 11) B2_barterGame.json
B3_barterGame.json
(71, 11) B3_barterGame.json
(71, 11) B3_barterGame.json
B4_barterGame.json
(46, 11) B4_barterGame.json
(46, 11) B4_barterGame.json
B5_barterGame.json
(113, 13) B5_barterGame.json
(113, 13) B5_barterGame.json
B6_barterGame.json
(99, 13) B6_barterGame.json
(99, 13) B6_barterGame.json
C1_barterGame.json
(42, 11) C1_barterGame.json
(42, 11) C1_barterGame.json
C2_barterGame.json
(79, 11) C2_barterGame.json
(79, 11) C2_barterGame.json
C3_barterGame.json
(107, 11) C3_barterGame.json
(107, 11) C3_barterGame.json
C4_barterGame.json
(106, 13) C4_barterGame.json
(106, 13) C4_barterGame.json
C5_barterGame.json
(50, 13) C5_barterGame.json
(50, 13) C5_barterGame.json
C6_barterGame.json
(93, 13) C6_barterGame.json
(93, 13) C6_barterGame.json
C7_barterGame.txt
(64, 13) C7_barterGame.txt
(64, 13) C7_barterGame.txt

In [6]:
tierItemsValueFile=open('TierITemValues.txt', encoding='utf8')
tierItemsValuelines = tierItemsValueFile.readlines()
tierItemsValueFile.close()

item_names_list = []
item_tier_list = []
item_value_list = []
itemTierValue_dict = {}
profession_items_dict = {profession: [] for profession in professions_set}

for line in tierItemsValuelines:
    # print(line)
    if 'tier1' in line:
        item_name = line.split('ItemStack(Material.')[1].split('));')[0]
        item_name = item_name.lower()
        # item_names_list.append(item_name)
        # item_tier_list.append(1)
        # item_value_list.append(1)
        # print(line)
        profession_name = line.split('tier1')[1].split('.add(')[0]
        profession_items_dict[profession_name].append(item_name)
        if item_name not in itemTierValue_dict:
            itemTierValue_dict[item_name] = {'tier': 1, 'value':1}
    elif 'tier2' in line:
        item_name = line.split('ItemStack(Material.')[1].split('));')[0]
        item_name = item_name.lower()
        # item_names_list.append(item_name)
        # item_tier_list.append(2)
        # item_value_list.append(3)
        # print(line)
        profession_name = line.split('tier2')[1].split('.add(')[0]
        profession_items_dict[profession_name].append(item_name)
        if item_name not in itemTierValue_dict:
            itemTierValue_dict[item_name] = {'tier': 2, 'value':3}
    elif 'tier3' in line:
        item_name = line.split('ItemStack(Material.')[1].split('));')[0]
        item_name = item_name.lower()
        # item_names_list.append(item_name)
        # item_tier_list.append(3)
        # item_value_list.append(10)
        # print(line)
        profession_name = line.split('tier3')[1].split('.add(')[0]
        profession_items_dict[profession_name].append(item_name)
        if item_name not in itemTierValue_dict:
            itemTierValue_dict[item_name] = {'tier': 3, 'value':10}

# itemTierValue_df = df({'item_name':item_names_list, 'tier':item_tier_list, 'value':item_value_list})
print(itemTierValue_dict)
print(profession_items_dict)

{'potato': {'tier': 1, 'value': 1}, 'carrot': {'tier': 1, 'value': 1}, 'wheat': {'tier': 1, 'value': 1}, 'bread': {'tier': 2, 'value': 3}, 'pumpkin': {'tier': 2, 'value': 3}, 'mushroom_stew': {'tier': 3, 'value': 10}, 'cod': {'tier': 1, 'value': 1}, 'salmon': {'tier': 1, 'value': 1}, 'tropical_fish': {'tier': 1, 'value': 1}, 'pufferfish': {'tier': 2, 'value': 3}, 'turtle_egg': {'tier': 2, 'value': 3}, 'oak_boat': {'tier': 3, 'value': 10}, 'beef': {'tier': 1, 'value': 1}, 'chicken': {'tier': 1, 'value': 1}, 'porkchop': {'tier': 1, 'value': 1}, 'cooked_beef': {'tier': 2, 'value': 3}, 'cooked_porkchop': {'tier': 2, 'value': 3}, 'rabbit_stew': {'tier': 3, 'value': 10}, 'iron_ingot': {'tier': 1, 'value': 1}, 'gold_ingot': {'tier': 1, 'value': 1}, 'coal': {'tier': 1, 'value': 1}, 'fletching_table': {'tier': 2, 'value': 3}, 'smithing_table': {'tier': 2, 'value': 3}, 'diamond_sword': {'tier': 3, 'value': 10}, 'leather': {'tier': 1, 'value': 1}, 'stick': {'tier': 1, 'value': 1}, 'lead': {'tier': 1, 'value': 1}, 'cow_spawn_egg': {'tier': 2, 'value': 3}, 'rabbit_hide': {'tier': 2, 'value': 3}, 'saddle': {'tier': 3, 'value': 10}, 'stone': {'tier': 1, 'value': 1}, 'quartz_block': {'tier': 1, 'value': 1}, 'glass': {'tier': 1, 'value': 1}, 'red_glazed_terracotta': {'tier': 2, 'value': 3}, 'blue_glazed_terracotta': {'tier': 2, 'value': 3}, 'stone_pickaxe': {'tier': 3, 'value': 10}, 'string': {'tier': 1, 'value': 1}, 'white_wool': {'tier': 1, 'value': 1}, 'blue_dye': {'tier': 1, 'value': 1}, 'sheep_spawn_egg': {'tier': 2, 'value': 3}, 'loom': {'tier': 2, 'value': 3}, 'shears': {'tier': 3, 'value': 10}, 'oak_log': {'tier': 1, 'value': 1}, 'spruce_log': {'tier': 1, 'value': 1}, 'birch_log': {'tier': 1, 'value': 1}, 'spruce_planks': {'tier': 2, 'value': 3}, 'oak_planks': {'tier': 2, 'value': 3}, 'diamond_axe': {'tier': 3, 'value': 10}}
{'Fisher': ['cod', 'salmon', 'tropical_fish', 'pufferfish', 'turtle_egg', 'oak_boat'], 'Butcher': ['beef', 'chicken', 'porkchop', 'cooked_beef', 'cooked_porkchop', 'rabbit_stew'], 'Lumberjack': ['oak_log', 'spruce_log', 'birch_log', 'spruce_planks', 'oak_planks', 'diamond_axe'], 'Blacksmith': ['iron_ingot', 'gold_ingot', 'coal', 'fletching_table', 'smithing_table', 'diamond_sword'], 'Shepherd': ['string', 'white_wool', 'blue_dye', 'sheep_spawn_egg', 'loom', 'shears'], 'Farmer': ['potato', 'carrot', 'wheat', 'bread', 'pumpkin', 'mushroom_stew'], 'Leatherworker': ['leather', 'stick', 'lead', 'cow_spawn_egg', 'rabbit_hide', 'saddle'], 'Mason': ['stone', 'quartz_block', 'glass', 'red_glazed_terracotta', 'blue_glazed_terracotta', 'stone_pickaxe']}

In [7]:
TIER1_VALUE = 1
TIER2_VALUE = 3
TIER3_VALUE = 10

tier_items=pd.read_excel('exp.xlsx')
# print(tier_items)
tier3_items_set=set(list(tier_items["Tier 3"][tier_items["Tier 3"].notnull()].values))
tier2_items_set=set(list(tier_items["Tier 2"][tier_items["Tier 2"].notnull()].values))
tier1_items_set=set(list(tier_items["Tier 1"][tier_items["Tier 1"].notnull()].values))
# print('tier3 items: ', tier3_items_set, len(tier3_items_set))
# print('tier2 items: ', tier2_items_set, len(tier2_items_set))
# print('tier1 items: ', tier1_items_set, len(tier1_items_set))
tier1_items_list = [item.lower().replace(' ', '_') for item in tier1_items_set]
tier2_items_list = [item.lower().replace(' ', '_') for item in tier2_items_set]
tier3_items_list = [item.lower().replace(' ', '_') for item in tier3_items_set]
print('tier3 items: ', tier3_items_list, len(tier3_items_list))
print('tier2 items: ', tier2_items_list, len(tier2_items_list))
print('tier1 items: ', tier1_items_list, len(tier1_items_list))

tier3 items:  ['diamond_sword', 'chiseled_quartz_block', 'shears', 'diamond_axe', 'rabbit_stew', 'mushroom_stew', 'cow_spawn_egg', 'oak_boat', 'sheep_spawn_egg'] 9
tier2 items:  ['tadpole_bucket', 'pufferfish', 'blue_glazed_terracotta', 'smithing_table', 'saddle', 'red_glazed_terracotta', 'iron_sword', 'spruce_log', 'cooked_beef', 'golden_pickaxe', 'birch_log', 'rabbit_hide', 'bread', 'cooked_porkchop', 'oak_log', 'loom', 'pumpkin'] 17
tier1 items:  ['oak_planks', 'salmon', 'carrot', 'blue_dye', 'white_wool', 'leather', 'string', 'terracotta', 'coal', 'beef', 'leather_boots', 'cod', 'porkchop', 'stone', 'birch_planks', 'iron_ingot', 'spruce_planks', 'tropical_fish', 'stick', 'potato', 'gold_ingot', 'wheat', 'glass', 'chicken'] 24

In [8]:
def get_trade_value(r):
    request_list = r['request']
    offer_list = r['offer']
    total_trade_value = 0
    for req in request_list:
        item_name = req['resource']
        item_num = req['amount']
        item_name = item_name.lower().replace(' ', '_')
        if item_name in itemTierValue_dict:
            total_value = itemTierValue_dict[item_name]['value'] * item_num
            total_trade_value += total_value
        else:
            # use exp.xlsx
            if item_name in tier1_items_list:
                total_trade_value += (item_num * TIER1_VALUE)
            elif item_name in tier2_items_list:
                total_trade_value += (item_num * TIER2_VALUE)
            elif item_name in tier3_items_list:
                total_trade_value += (item_num * TIER3_VALUE)
            else:
                # unable to find this item in the tier value directory
                print('unable to find tier value: ', item_name)
    for req in offer_list:
        item_name = req['resource']
        item_num = req['amount']
        item_name = item_name.lower().replace(' ', '_')
        if item_name in itemTierValue_dict:
            total_value = itemTierValue_dict[item_name]['value'] * item_num
            total_trade_value += total_value
        else:
            # use exp.xlsx
            if item_name in tier1_items_list:
                total_trade_value += (item_num * TIER1_VALUE)
            elif item_name in tier2_items_list:
                total_trade_value += (item_num * TIER2_VALUE)
            elif item_name in tier3_items_list:
                total_trade_value += (item_num * TIER3_VALUE)
            else:
                # unable to find this item in the tier value directory
                print('unable to find tier value: ', item_name)
            
    r['trade_value'] = total_trade_value
    r['game_name'] = filename.split('_')[0]
    if 'A' in filename.split('_')[0]:
        r['game_type'] = 'Competitive'
    elif 'B' in filename.split('_')[0]:
        r['game_type'] = 'Baseline'
    else:
        r['game_type'] = 'Cooperative'
    return r

In [9]:
for filename in game_trades_df_dict:
    print(filename)
    trades_df = game_trades_df_dict[filename]
    trades_df = trades_df.apply(get_trade_value, axis=1)
    game_trades_df_dict[filename] = trades_df

A1_barterGame.json
A2_barterGame.json
A3_barterGame.json
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
A4_barterGame.json
A5_barterGame.json
A6_barterGame.json
unable to find tier value:  crafting_table
unable to find tier value:  written_book
unable to find tier value:  written_book
A7_barterGame.txt
B1_barterGame.json
unable to find tier value:  carrots
B2_barterGame.json
B3_barterGame.json
B4_barterGame.json
B5_barterGame.json
B6_barterGame.json
C1_barterGame.json
unable to find tier value:  emerald
unable to find tier value:  emerald
unable to find tier value:  emerald
unable to find tier value:  emerald
C2_barterGame.json
C3_barterGame.json
C4_barterGame.json
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
C5_barterGame.json
C6_barterGame.json
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
unable to find tier value:  written_book
C7_barterGame.txt
unable to find tier value:  rotten_flesh

In [10]:
def get_request_non_useful_items(trades_df, player_names_list, player_profession_dict, profession_items_dict, filename):
    player_profession = {}
    player_useful_items = {}
    for player in player_names_list:
        player_profession[player] = player_profession_dict[filename][player]
        player_useful_items[player] = profession_items_dict[player_profession[player]]
    def row_wise_non_useful(row):
        p1 = row['requester']
        p2 = row['requested']

        request_list = row['request']
        request_items_list = [ent['resource'].lower().replace(' ', '_') for ent in request_list]
        request_non_useful_items_list = [item for item in request_items_list if item not in player_useful_items[p1]]
        # request_non_useful_amount_list = [item for item in request_non_useful_items_list if item not in player_useful_items[p1]]
        
        offer_list = row['offer']
        offer_items_list = [ent['resource'].lower().replace(' ', '_') for ent in offer_list]
        offer_non_useful_items_list = [item for item in offer_items_list if item not in player_useful_items[p2]]
        row['requester_nonuseful'] = request_non_useful_items_list
        # row['requester_nonuseful_amount'] = 
        row['requested_nonuseful'] = offer_non_useful_items_list
        return row

    trades_df = trades_df.apply(row_wise_non_useful, axis=1)
    return trades_df

In [27]:
player_beginscore_dict = {}
nonuseful_filenames_list = []

for filename in ['C1_barterGame.json']: #game_trades_df_dict:
    print('##############')
    print(filename)
    trades_df = game_trades_df_dict[filename]
    player_names_list = list(set(player_profession_dict[filename].keys()))
    trades_df = get_request_non_useful_items(trades_df, player_names_list, player_profession_dict, profession_items_dict, filename)
    if 'beginScores' not in trades_df.columns:
        print('beginscores column not present')
        nonuseful_filenames_list.append(filename)
        print('##############')
        continue
    player_beginscore_dict[filename] = []
    for player in ['SnoopHoggFan']: #player_names_list:
        print(player)
        x_df = trades_df[(trades_df['requester']==player) | (trades_df['requested']==player)]
        if x_df.iloc[0,:]['requester'] == player:
            player_beginscore = x_df.iloc[0,:]['beginScores']['requester']
        elif x_df.iloc[0,:]['requested'] == player:
            player_beginscore = x_df.iloc[0,:]['beginScores']['requested']
        print(player_beginscore)
        player_beginscore_dict[filename].append(
            {'player': player, 'beginScore': player_beginscore,
             'endScore': player_endscores_dict[filename][player],
             'game_type': x_df.iloc[0,:]['game_type'], 'game_name': x_df.iloc[0,:]['game_name']})

##############
C1_barterGame.json
SnoopHoggFan
24

In [30]:
x_df.loc[3,'offer'], x_df.loc[3,'request']

([{'amount': 8, 'resource': 'Bread'},
  {'amount': 1, 'resource': 'Carrot'},
  {'amount': 10, 'resource': 'Beef'},
  {'amount': 10, 'resource': 'Wheat'}],
 [{'amount': 2, 'resource': 'Oak Log'},
  {'amount': 15, 'resource': 'Oak Planks'},
  {'amount': 1, 'resource': 'Spruce Log'},
  {'amount': 2, 'resource': 'Birch Planks'},
  {'amount': 2, 'resource': 'White Wool'}])

In [29]:
x_df

,requester,offer,request,requested,beginTimestamp,endScores,requestID,beginScores,endTimestamp,hasMenu,status,trade_value,game_name,game_type,requester_nonuseful,requested_nonuseful
0,SnoopHoggFan,[],[],ImJustAManiac,2023-04-06 18:29:07.033,"{'requester': 24, 'requested': 24}",SnoopHoggFanImJustAManiac1680820147033,"{'requester': 24, 'requested': 24}",2023-04-06 18:29:16.913,True,CANCELLED,0,C1,Cooperative,[],[]
1,ImJustAManiac,"[{'amount': 5, 'resource': 'Pumpkin'}]","[{'amount': 16, 'resource': 'String'}]",SnoopHoggFan,2023-04-06 18:29:26.429,"{'requester': 55, 'requested': 55}",ImJustAManiacSnoopHoggFan1680820166429,"{'requester': 39, 'requested': 39}",2023-04-06 18:29:40.677,True,ACCEPTED,31,C1,Cooperative,[],[pumpkin]
3,SnoopHoggFan,"[{'amount': 8, 'resource': 'Bread'}, {'amount'...","[{'amount': 2, 'resource': 'Oak Log'}, {'amoun...",godh3ad,2023-04-06 18:30:08.132,"{'requester': 50, 'requested': 50}",SnoopHoggFangodh3ad1680820208132,"{'requester': 24, 'requested': 24}",2023-04-06 18:30:33.369,True,ACCEPTED,97,C1,Cooperative,"[birch_planks, white_wool]","[bread, carrot, wheat]"
4,SnoopHoggFan,"[{'amount': 1, 'resource': 'Sheep Spawn Egg'}]","[{'amount': 3, 'resource': 'Potato'}]",ImJustAManiac,2023-04-06 18:31:00.987,"{'requester': 50, 'requested': 50}",SnoopHoggFanImJustAManiac1680820260987,"{'requester': 50, 'requested': 50}",2023-04-06 18:31:10.864,True,ACCEPTED,6,C1,Cooperative,[potato],[]
8,ImJustAManiac,"[{'amount': 4, 'resource': 'Oak Planks'}, {'am...","[{'amount': 1, 'resource': 'Quartz Block'}, {'...",SnoopHoggFan,2023-04-06 18:32:12.161,"{'requester': 79, 'requested': 79}",ImJustAManiacSnoopHoggFan1680820332161,"{'requester': 64, 'requested': 64}",2023-04-06 18:32:29.039,True,ACCEPTED,41,C1,Cooperative,[quartz_block],[glass]
9,SnoopHoggFan,"[{'amount': 15, 'resource': 'Glass'}, {'amount...","[{'amount': 1, 'resource': 'Spruce Log'}, {'am...",labrat2368,2023-04-06 18:32:42.633,"{'requester': 58, 'requested': 58}",SnoopHoggFanlabrat23681680820362633,"{'requester': 54, 'requested': 54}",2023-04-06 18:33:03.414,True,ACCEPTED,101,C1,Cooperative,"[cooked_beef, cooked_porkchop]","[glass, stone_pickaxe]"
10,SnoopHoggFan,[],[],_Mim_,2023-04-06 18:33:06.479,"{'requester': 58, 'requested': 58}",SnoopHoggFan_Mim_1680820386479,"{'requester': 58, 'requested': 58}",2023-04-06 18:33:17.675,True,DECLINED,0,C1,Cooperative,[],[]
12,_Mim_,"[{'amount': 1, 'resource': 'Diamond Axe'}, {'a...","[{'amount': 9, 'resource': 'Cooked Porkchop'}]",SnoopHoggFan,2023-04-06 18:33:45.216,"{'requester': 72, 'requested': 72}",_Mim_SnoopHoggFan1680820425216,"{'requester': 72, 'requested': 72}",2023-04-06 18:34:06.063,True,ACCEPTED,47,C1,Cooperative,[cooked_porkchop],[]
16,SnoopHoggFan,"[{'amount': 9, 'resource': 'Cooked Beef'}]","[{'amount': 1, 'resource': 'String'}]",godh3ad,2023-04-06 18:35:30.681,"{'requester': 78, 'requested': 78}",SnoopHoggFangodh3ad1680820530681,"{'requester': 78, 'requested': 78}",2023-04-06 18:35:45.500,True,ACCEPTED,28,C1,Cooperative,[string],[]
18,SnoopHoggFan,"[{'amount': 1, 'resource': 'String'}]","[{'amount': 3, 'resource': 'Oak Planks'}]",ImJustAManiac,2023-04-06 18:37:05.285,"{'requester': 81, 'requested': 81}",SnoopHoggFanImJustAManiac1680820625285,"{'requester': 78, 'requested': 78}",2023-04-06 18:37:12.447,True,ACCEPTED,10,C1,Cooperative,[],[]
19,SnoopHoggFan,"[{'amount': 1, 'resource': 'Birch Planks'}]","[{'amount': 6, 'resource': 'Spruce Log'}]",_Mim_,2023-04-06 18:37:23.387,"{'requester': 98, 'requested': 98}",SnoopHoggFan_Mim_1680820643387,"{'requester': 81, 'requested': 81}",2023-04-06 18:37:49.762,True,ACCEPTED,7,C1,Cooperative,[],[birch_planks]
25,_Mim_,[],[],SnoopHoggFan,2023-04-06 18:43:16.893,"{'requester': 92, 'requested': 92}",_Mim_SnoopHoggFan1680820996893,"{'requester': 92, 'requested': 92}",2023-04-06 18:43:23.188,True,DECLINED,0,C1,Cooperative,[],[]
29,_Mim_,"[{'amount': 16, 'resource': 'Spruce Planks'}, ...","[{'amount': 1, 'resource': 'Birch Planks'}]",SnoopHoggFan,2023-04-06 18:43:27.798,"{'requester': 92, 'requested': 92}",_Mim_SnoopHoggFan1680821007798,"{'requester': 92, 'requested': 92}",2023-04-06 18:43:37.727,True,ACCEPTED,67,C1,Cooperative,[birch_planks],[birch_planks]
30,SnoopHoggFan,[],[],godh3ad,2023-04-06 18:43:48.887,"{'requester': 130, 'requested': 130}",SnoopHoggFangodh3ad1680821028887,"{'requester': 131, 'requested': 131}",2023-04-06 18:44:04.829,True,DECLINED,0,C1,Cooperative,[],[]
36,godh3ad,[],[],SnoopHoggFan,2023-04-06 18:54:25.675,"{'requester': 135, 'requested': 135}",godh3adSnoopHoggFan1680821665675,"{'requester': 135, 'requested': 135}",2023-04-06 18:54:27.989,True,DECLINED,0,C1,Cooperative,[],[]
37,godh3ad,[],[],SnoopHoggFan,2023-04-06 18:54:29.162,"{'requester': 135, 'requested': 135}",godh3adSnoopHoggFan1680821669162,"{'requester': 135, 'requested': 135}",2023-04-06 18:54:30.079,True,DECLINED,0,C1,Cooperative,[],[]
39,ImJustAManiac,"[{'amount': 12, 'resource': 'Chicken'}]","[{'amount': 1, 'resource': 'Oak Planks'}]",SnoopHoggFan,2023-04-06 18:55:15.040,"{'requester': 135, 'requested': 135}",ImJustAManiacSnoopHoggFan2023-04-06 18:55:15.04,"{'requester': 135, 'requested': 135}",2023-04-06 18:55:19.824,False,ACCEPTED,15,C1,Cooperative,[oak_planks],[chicken]
40,SnoopHoggFan,"[{'amount': 12, 'resource': 'Chicken'}]","[{'amount': 1, 'resource': 'Emerald'}]",godh3ad,2023-04-06 18:55:31.591,"{'requester': 138, 'requested': 138}",SnoopHoggFangodh3ad1680821731591,"{'requester': 138, 'requested': 138}",2023-04-06 18:55:41.524,True,ACCEPTED,12,C1,Cooperative,[emerald],[]

In [16]:
nonuseful_filenames_list

['A1_barterGame.json', 'B1_barterGame.json']

In [17]:
player_beginscore_dict

{'A2_barterGame.json': [{'player': 'TheSurvivorGuy',
   'beginScore': 40,
   'endScore': 110,
   'game_type': 'Competitive',
   'game_name': 'A2'},
  {'player': 'CJL2213',
   'beginScore': 25,
   'endScore': 89,
   'game_type': 'Competitive',
   'game_name': 'A2'},
  {'player': 'NerdyPiggy',
   'beginScore': 50,
   'endScore': 99,
   'game_type': 'Competitive',
   'game_name': 'A2'},
  {'player': 'ultimate_glory',
   'beginScore': 4,
   'endScore': 98,
   'game_type': 'Competitive',
   'game_name': 'A2'},
  {'player': 'BlackeyeBob345',
   'beginScore': 64,
   'endScore': 122,
   'game_type': 'Competitive',
   'game_name': 'A2'}],
 'A3_barterGame.json': [{'player': 'labrat2368',
   'beginScore': 4,
   'endScore': 53,
   'game_type': 'Competitive',
   'game_name': 'A3'},
  {'player': 'notAbdullah_',
   'beginScore': 33,
   'endScore': 63,
   'game_type': 'Competitive',
   'game_name': 'A3'},
  {'player': 'JaredTheBossJla',
   'beginScore': 10,
   'endScore': 67,
   'game_type': 'Competitive',
   'game_name': 'A3'},
  {'player': 'Xaxaura',
   'beginScore': 26,
   'endScore': 88,
   'game_type': 'Competitive',
   'game_name': 'A3'},
  {'player': 'kalyaniplays',
   'beginScore': 43,
   'endScore': 89,
   'game_type': 'Competitive',
   'game_name': 'A3'}],
 'A4_barterGame.json': [{'player': 'BLK_Cloud6',
   'beginScore': 22,
   'endScore': 43,
   'game_type': 'Competitive',
   'game_name': 'A4'},
  {'player': 'Mumen_Crafter',
   'beginScore': 46,
   'endScore': 87,
   'game_type': 'Competitive',
   'game_name': 'A4'},
  {'player': 'coolbrd',
   'beginScore': 34,
   'endScore': 119,
   'game_type': 'Competitive',
   'game_name': 'A4'},
  {'player': 'CrashCringle12',
   'beginScore': 39,
   'endScore': 79,
   'game_type': 'Competitive',
   'game_name': 'A4'},
  {'player': 'firewolfy2451',
   'beginScore': 43,
   'endScore': 100,
   'game_type': 'Competitive',
   'game_name': 'A4'}],
 'A5_barterGame.json': [{'player': 'Rh75',
   'beginScore': 47,
   'endScore': 150,
   'game_type': 'Competitive',
   'game_name': 'A5'},
  {'player': 'Ethan2098',
   'beginScore': 35,
   'endScore': 150,
   'game_type': 'Competitive',
   'game_name': 'A5'},
  {'player': 'wns',
   'beginScore': 22,
   'endScore': 123,
   'game_type': 'Competitive',
   'game_name': 'A5'},
  {'player': 'PandaEatNoodle',
   'beginScore': 7,
   'endScore': 148,
   'game_type': 'Competitive',
   'game_name': 'A5'},
  {'player': 'Dallachaos',
   'beginScore': 57,
   'endScore': 150,
   'game_type': 'Competitive',
   'game_name': 'A5'}],
 'A6_barterGame.json': [{'player': 'labrat2368',
   'beginScore': 17,
   'endScore': 93,
   'game_type': 'Competitive',
   'game_name': 'A6'},
  {'player': 'DarthKittie',
   'beginScore': 37,
   'endScore': 514,
   'game_type': 'Competitive',
   'game_name': 'A6'},
  {'player': 'DENISOVICH704',
   'beginScore': 35,
   'endScore': 40,
   'game_type': 'Competitive',
   'game_name': 'A6'},
  {'player': 'TDAbos5',
   'beginScore': 25,
   'endScore': 139,
   'game_type': 'Competitive',
   'game_name': 'A6'},
  {'player': 'chehukyu',
   'beginScore': 14,
   'endScore': 83,
   'game_type': 'Competitive',
   'game_name': 'A6'},
  {'player': 'Stargirl344',
   'beginScore': 20,
   'endScore': 117,
   'game_type': 'Competitive',
   'game_name': 'A6'},
  {'player': 'hollyarden03',
   'beginScore': 36,
   'endScore': 91,
   'game_type': 'Competitive',
   'game_name': 'A6'}],
 'A7_barterGame.txt': [{'player': 'JoeyTheSoda',
   'beginScore': 13,
   'endScore': 131,
   'game_type': 'Competitive',
   'game_name': 'A7'},
  {'player': 'Phoned_Leek25',
   'beginScore': 1,
   'endScore': 83,
   'game_type': 'Competitive',
   'game_name': 'A7'},
  {'player': 'SepticSteak',
   'beginScore': 38,
   'endScore': 147,
   'game_type': 'Competitive',
   'game_name': 'A7'},
  {'player': 'ppcruncher',
   'beginScore': 27,
   'endScore': 121,
   'game_type': 'Competitive',
   'game_name': 'A7'},
  {'player': 'kalyaniplays',
   'beginScore': 14,
   'endScore': 144,
   'game_type': 'Competitive',
   'game_name': 'A7'}],
 'B2_barterGame.json': [{'player': 'z_man614',
   'beginScore': 25,
   'endScore': 69,
   'game_type': 'Baseline',
   'game_name': 'B2'},
  {'player': 'StraySimian',
   'beginScore': 61,
   'endScore': 111,
   'game_type': 'Baseline',
   'game_name': 'B2'},
  {'player': 'ArcticPuma8386',
   'beginScore': 30,
   'endScore': 91,
   'game_type': 'Baseline',
   'game_name': 'B2'},
  {'player': 'DarkLordPYRO',
   'beginScore': 61,
   'endScore': 90,
   'game_type': 'Baseline',
   'game_name': 'B2'},
  {'player': 'ThatOtherGuy0',
   'beginScore': 25,
   'endScore': 119,
   'game_type': 'Baseline',
   'game_name': 'B2'}],
 'B3_barterGame.json': [{'player': 'T_rista',
   'beginScore': 31,
   'endScore': 150,
   'game_type': 'Baseline',
   'game_name': 'B3'},
  {'player': 'lytil',
   'beginScore': 60,
   'endScore': 150,
   'game_type': 'Baseline',
   'game_name': 'B3'},
  {'player': 'Chestnaught65',
   'beginScore': 21,
   'endScore': 132,
   'game_type': 'Baseline',
   'game_name': 'B3'},
  {'player': 'Voxhales',
   'beginScore': 27,
   'endScore': 139,
   'game_type': 'Baseline',
   'game_name': 'B3'},
  {'player': 'reglemorph',
   'beginScore': 6,
   'endScore': 133,
   'game_type': 'Baseline',
   'game_name': 'B3'}],
 'B4_barterGame.json': [{'player': 'bat600013',
   'beginScore': 13,
   'endScore': 70,
   'game_type': 'Baseline',
   'game_name': 'B4'},
  {'player': 'evilsaloon',
   'beginScore': 8,
   'endScore': 83,
   'game_type': 'Baseline',
   'game_name': 'B4'},
  {'player': 'NightScythe1',
   'beginScore': 28,
   'endScore': 118,
   'game_type': 'Baseline',
   'game_name': 'B4'},
  {'player': 'kalyaniplays',
   'beginScore': 21,
   'endScore': 110,
   'game_type': 'Baseline',
   'game_name': 'B4'},
  {'player': 'Joey1_Joey2',
   'beginScore': 53,
   'endScore': 103,
   'game_type': 'Baseline',
   'game_name': 'B4'}],
 'B5_barterGame.json': [{'player': 'labrat2368',
   'beginScore': 24,
   'endScore': 99,
   'game_type': 'Baseline',
   'game_name': 'B5'},
  {'player': '1SGTKu',
   'beginScore': 9,
   'endScore': 120,
   'game_type': 'Baseline',
   'game_name': 'B5'},
  {'player': 'F5tar',
   'beginScore': 14,
   'endScore': 100,
   'game_type': 'Baseline',
   'game_name': 'B5'},
  {'player': 'Jimster0801',
   'beginScore': 6,
   'endScore': 94,
   'game_type': 'Baseline',
   'game_name': 'B5'},
  {'player': 'JaredTheBossJla',
   'beginScore': 7,
   'endScore': 74,
   'game_type': 'Baseline',
   'game_name': 'B5'},
  {'player': 'kalyaniplays',
   'beginScore': 33,
   'endScore': 100,
   'game_type': 'Baseline',
   'game_name': 'B5'}],
 'B6_barterGame.json': [{'player': 'RafshanRehan',
   'beginScore': 22,
   'endScore': 118,
   'game_type': 'Baseline',
   'game_name': 'B6'},
  {'player': 'SQUEAKERLOO999',
   'beginScore': 5,
   'endScore': 125,
   'game_type': 'Baseline',
   'game_name': 'B6'},
  {'player': 'BeepyBoi',
   'beginScore': 59,
   'endScore': 132,
   'game_type': 'Baseline',
   'game_name': 'B6'},
  {'player': 'SSCCPP',
   'beginScore': 41,
   'endScore': 110,
   'game_type': 'Baseline',
   'game_name': 'B6'},
  {'player': 'SajNinja',
   'beginScore': 18,
   'endScore': 123,
   'game_type': 'Baseline',
   'game_name': 'B6'},
  {'player': 'FeelsBadCat',
   'beginScore': 68,
   'endScore': 121,
   'game_type': 'Baseline',
   'game_name': 'B6'}],
 'C1_barterGame.json': [{'player': 'labrat2368',
   'beginScore': 24,
   'endScore': 78,
   'game_type': 'Cooperative',
   'game_name': 'C1'},
  {'player': 'SnoopHoggFan',
   'beginScore': 24,
   'endScore': 138,
   'game_type': 'Cooperative',
   'game_name': 'C1'},
  {'player': 'godh3ad',
   'beginScore': 24,
   'endScore': 147,
   'game_type': 'Cooperative',
   'game_name': 'C1'},
  {'player': '_Mim_',
   'beginScore': 24,
   'endScore': 135,
   'game_type': 'Cooperative',
   'game_name': 'C1'},
  {'player': 'ImJustAManiac',
   'beginScore': 24,
   'endScore': 135,
   'game_type': 'Cooperative',
   'game_name': 'C1'}],
 'C2_barterGame.json': [{'player': 'alecxzh',
   'beginScore': 3,
   'endScore': 139,
   'game_type': 'Cooperative',
   'game_name': 'C2'},
  {'player': 'YukinoChanX',
   'beginScore': 24,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C2'},
  {'player': 'Nyathaleen',
   'beginScore': 26,
   'endScore': 139,
   'game_type': 'Cooperative',
   'game_name': 'C2'},
  {'player': 'MajesticLlama3',
   'beginScore': 7,
   'endScore': 146,
   'game_type': 'Cooperative',
   'game_name': 'C2'},
  {'player': 'SilverFuryDXB18',
   'beginScore': 33,
   'endScore': 140,
   'game_type': 'Cooperative',
   'game_name': 'C2'},
  {'player': 'BaneOfHades',
   'beginScore': 38,
   'endScore': 141,
   'game_type': 'Cooperative',
   'game_name': 'C2'}],
 'C3_barterGame.json': [{'player': 'JMS1717',
   'beginScore': 22,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C3'},
  {'player': 'diver2212',
   'beginScore': 11,
   'endScore': 146,
   'game_type': 'Cooperative',
   'game_name': 'C3'},
  {'player': 'abbawei',
   'beginScore': 33,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C3'},
  {'player': 'brokedad',
   'beginScore': 32,
   'endScore': 147,
   'game_type': 'Cooperative',
   'game_name': 'C3'},
  {'player': 'LogicBlender',
   'beginScore': 41,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C3'}],
 'C4_barterGame.json': [{'player': 'oldseahag4',
   'beginScore': 13,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C4'},
  {'player': 'andyyv',
   'beginScore': 18,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C4'},
  {'player': 'thebigzucch',
   'beginScore': 51,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C4'},
  {'player': 'carmennphamm',
   'beginScore': 11,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C4'},
  {'player': 'reallysui',
   'beginScore': 20,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C4'},
  {'player': 'TheNotoriousSAM',
   'beginScore': 25,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C4'}],
 'C5_barterGame.json': [{'player': 'z3rohedgehog',
   'beginScore': 55,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C5'},
  {'player': 'lovelyy',
   'beginScore': 57,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C5'},
  {'player': 'Cyndakip0',
   'beginScore': 63,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C5'},
  {'player': 'kalyaniplays',
   'beginScore': 32,
   'endScore': 127,
   'game_type': 'Cooperative',
   'game_name': 'C5'},
  {'player': 'J_bobaa',
   'beginScore': 33,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C5'}],
 'C6_barterGame.json': [{'player': 'PointBreak9819',
   'beginScore': 0,
   'endScore': 121,
   'game_type': 'Cooperative',
   'game_name': 'C6'},
  {'player': 'IrisQuasar',
   'beginScore': 37,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C6'},
  {'player': 'PrvtParts',
   'beginScore': 0,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C6'},
  {'player': 'Panda22456',
   'beginScore': 27,
   'endScore': 145,
   'game_type': 'Cooperative',
   'game_name': 'C6'},
  {'player': 'Stadelbob',
   'beginScore': 51,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C6'}],
 'C7_barterGame.txt': [{'player': 'Protocol0',
   'beginScore': 39,
   'endScore': 123,
   'game_type': 'Cooperative',
   'game_name': 'C7'},
  {'player': 'AndrewLukkuz',
   'beginScore': 49,
   'endScore': 142,
   'game_type': 'Cooperative',
   'game_name': 'C7'},
  {'player': 'Archangel6266',
   'beginScore': 46,
   'endScore': 150,
   'game_type': 'Cooperative',
   'game_name': 'C7'},
  {'player': 'firestar5467',
   'beginScore': 18,
   'endScore': 135,
   'game_type': 'Cooperative',
   'game_name': 'C7'},
  {'player': 'OrganicSugar',
   'beginScore': 7,
   'endScore': 125,
   'game_type': 'Cooperative',
   'game_name': 'C7'}]}

In [18]:
player_beginscore_dict = {filename: df.from_records(player_beginscore_dict[filename]) for filename in player_beginscore_dict if player_beginscore_dict[filename] != []}
player_beginscore_dict.keys()

dict_keys(['A2_barterGame.json', 'A3_barterGame.json', 'A4_barterGame.json', 'A5_barterGame.json', 'A6_barterGame.json', 'A7_barterGame.txt', 'B2_barterGame.json', 'B3_barterGame.json', 'B4_barterGame.json', 'B5_barterGame.json', 'B6_barterGame.json', 'C1_barterGame.json', 'C2_barterGame.json', 'C3_barterGame.json', 'C4_barterGame.json', 'C5_barterGame.json', 'C6_barterGame.json', 'C7_barterGame.txt'])

In [19]:
master_player_beginscore_df = df(columns=player_beginscore_dict[filename].columns)
print(master_player_beginscore_df.shape)
for filename in player_beginscore_dict:
    master_player_beginscore_df = pd.concat([master_player_beginscore_df, player_beginscore_dict[filename]])
    print(filename, player_beginscore_dict[filename].shape, master_player_beginscore_df.shape)    
master_player_beginscore_df

(0, 5)
A2_barterGame.json (5, 5) (5, 5)
A3_barterGame.json (5, 5) (10, 5)
A4_barterGame.json (5, 5) (15, 5)
A5_barterGame.json (5, 5) (20, 5)
A6_barterGame.json (7, 5) (27, 5)
A7_barterGame.txt (5, 5) (32, 5)
B2_barterGame.json (5, 5) (37, 5)
B3_barterGame.json (5, 5) (42, 5)
B4_barterGame.json (5, 5) (47, 5)
B5_barterGame.json (6, 5) (53, 5)
B6_barterGame.json (6, 5) (59, 5)
C1_barterGame.json (5, 5) (64, 5)
C2_barterGame.json (6, 5) (70, 5)
C3_barterGame.json (5, 5) (75, 5)
C4_barterGame.json (6, 5) (81, 5)
C5_barterGame.json (5, 5) (86, 5)
C6_barterGame.json (5, 5) (91, 5)
C7_barterGame.txt (5, 5) (96, 5)

            player beginScore endScore    game_type game_name
0   TheSurvivorGuy         40      110  Competitive        A2
1          CJL2213         25       89  Competitive        A2
2       NerdyPiggy         50       99  Competitive        A2
3   ultimate_glory          4       98  Competitive        A2
4   BlackeyeBob345         64      122  Competitive        A2
..             ...        ...      ...          ...       ...
0        Protocol0         39      123  Cooperative        C7
1     AndrewLukkuz         49      142  Cooperative        C7
2    Archangel6266         46      150  Cooperative        C7
3     firestar5467         18      135  Cooperative        C7
4     OrganicSugar          7      125  Cooperative        C7

[96 rows x 5 columns]

In [20]:
master_player_beginscore_df.to_excel('Humans-beginscores-df.xlsx')